// swift-tools-version: 6.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

var cSettings: [CSetting] = [
    .headerSearchPath("mGBA/include"),
    .headerSearchPath("mGBA/src"),

    .define("M_CORE_GBA"),
    .define("DISABLE_THREADING"),
    .define("MGBA_STANDALONE"),
    .define("HAVE_STRDUP"),
    .define("HAVE_STRNDUP"),
    .define("HAVE_STRLCPY"),
    .define("HAVE_LOCALTIME_R"),
    .define("HAVE_LOCALE"),
    .define("HAVE_STRTOF_L"),
    .define("HAVE_SNPRINTF_L"),
    .define("HAVE_SETLOCALE"),
    .define("HAVE_XLOCALE"),
    .define("BUILD_STATIC"),

    .unsafeFlags([
        "-Wall",
        "-Wextra",
        "-Wno-missing-field-initializers",
        "-Werror=implicit-function-declaration",
        "-Werror=implicit-int",
    ]),
]

let package = Package(
    name: "mGBAWatchCore",
    platforms: [.iOS(.v14), .macOS(.v13), .watchOS(.v10)],
    products: [
        .library(name: "mGBAWatchCore", targets: ["mGBA"])
    ],
    dependencies: [],
    targets: [
        .target(
            name: "mGBA",
            sources: [
                "mGBA/src/core/bitmap-cache.c",
                "mGBA/src/core/cache-set.c",
                "mGBA/src/core/cheats.c",
                "mGBA/src/core/config.c",
                "mGBA/src/core/core.c",
                "mGBA/src/core/directories.c",
                "mGBA/src/core/input.c",
                "mGBA/src/core/interface.c",
                "mGBA/src/core/library.c",
                "mGBA/src/core/lockstep.c",
                "mGBA/src/core/log.c",
                "mGBA/src/core/map-cache.c",
                "mGBA/src/core/mem-search.c",
                "mGBA/src/core/rewind.c",
                "mGBA/src/core/serialize.c",
                "mGBA/src/core/sync.c",
                "mGBA/src/core/thread.c",
                "mGBA/src/core/tile-cache.c",
                "mGBA/src/core/timing.c",
                "mGBA/src/arm/arm.c",
                "mGBA/src/arm/decoder-arm.c",
                "mGBA/src/arm/decoder.c",
                "mGBA/src/arm/decoder-thumb.c",
                "mGBA/src/arm/isa-arm.c",
                "mGBA/src/arm/isa-thumb.c",
                "mGBA/src/gb/audio.c",
                "mGBA/src/gba/audio.c",
                "mGBA/src/gba/bios.c",
                "mGBA/src/gba/cart/ereader.c",
                "mGBA/src/gba/cart/gpio.c",
                "mGBA/src/gba/cart/matrix.c",
                "mGBA/src/gba/cart/vfame.c",
                "mGBA/src/gba/cheats.c",
                "mGBA/src/gba/cheats/codebreaker.c",
                "mGBA/src/gba/cheats/gameshark.c",
                "mGBA/src/gba/cheats/parv3.c",
                "mGBA/src/gba/core.c",
                "mGBA/src/gba/dma.c",
                "mGBA/src/gba/gba.c",
                "mGBA/src/gba/hle-bios.c",
                "mGBA/src/gba/input.c",
                "mGBA/src/gba/io.c",
                "mGBA/src/gba/memory.c",
                "mGBA/src/gba/overrides.c",
                "mGBA/src/gba/renderers/cache-set.c",
                "mGBA/src/gba/renderers/common.c",
                "mGBA/src/gba/renderers/gl.c",
                "mGBA/src/gba/renderers/software-bg.c",
                "mGBA/src/gba/renderers/software-mode0.c",
                "mGBA/src/gba/renderers/software-obj.c",
                "mGBA/src/gba/renderers/video-software.c",
                "mGBA/src/gba/savedata.c",
                "mGBA/src/gba/serialize.c",
                "mGBA/src/gba/sharkport.c",
                "mGBA/src/gba/sio.c",
                "mGBA/src/gba/sio/gbp.c",
                "mGBA/src/gba/sio/joybus.c",
                "mGBA/src/gba/timer.c",
                "mGBA/src/gba/video.c",
                "mGBA/src/util/circle-buffer.c",
                "mGBA/src/util/configuration.c",
                "mGBA/src/util/crc32.c",
                "mGBA/src/util/formatting.c",
                "mGBA/src/util/gbk-table.c",
                "mGBA/src/util/hash.c",
                "mGBA/src/util/string.c",
                "mGBA/src/util/table.c",
                "mGBA/src/util/vfs.c",
                "mGBA/src/util/convolve.c",
                "mGBA/src/util/elf-read.c",
                "mGBA/src/util/export.c",
                "mGBA/src/util/patch.c",
                "mGBA/src/util/patch-fast.c",
                "mGBA/src/util/patch-ips.c",
                "mGBA/src/util/patch-ups.c",
                "mGBA/src/util/png-io.c",
                "mGBA/src/util/ring-fifo.c",
                "mGBA/src/util/text-codec.c",
                "mGBA/src/util/vfs/vfs-mem.c",
                "mGBA/src/util/vfs/vfs-fifo.c",
                "mGBA/src/util/vfs/vfs-fd.c",
                "mGBA/src/util/vfs/vfs-dirent.c",
                "mGBA/src/util/memory.c",
                "mGBA/src/third-party/inih/ini.c",
                "mGBA/src/third-party/blip_buf/blip_buf.c",
                "mGBA/src/gba/sio/dolphin.c",
                "mGBA/src/gba/sio/lockstep.c",
                "mGBA/src/gba/extra/audio-mixer.c",
                "mGBA/src/gba/extra/battlechip.c",
                "mGBA/src/gba/extra/proxy.c",
                "mGBA/src/feature/commandline.c",
                "mGBA/src/feature/thread-proxy.c",
                "mGBA/src/feature/updater.c",
                "mGBA/src/feature/video-logger.c",
                // NOTE: these would be generated files
                "version.c",
            ],
            publicHeadersPath: "include",
            cSettings: cSettings,
        ),
    ]
)
